/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author Killuminati
 */
public class HomeAdm extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdm
     */
    public HomeAdm() {
        initComponents();
        setIcon();
        ImageIcon image = new ImageIcon(getClass().getResource("Etec-Cursos.png"));
        Image imag = image.getImage().getScaledInstance(JlblFotoTopo.getWidth(), JlblFotoTopo.getHeight(), Image.SCALE_SMOOTH);
        
        JlblFotoTopo.setIcon(new ImageIcon(imag));
        
        PromptSupport.setPrompt("Busca por nome", JtxtPesquisar);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, JtxtPesquisar);
         //PromptSupport.setFontStyle(Font.BOLD, JtxtPesquisar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnSair = new javax.swing.JButton();
        JlblFotoTopo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JtxtPesquisar = new javax.swing.JTextField();
        JbtnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPesquisa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Pesquisa");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(211, 233, 255));
        jPanel1.setLayout(null);

        JbtnSair.setBackground(new java.awt.Color(204, 0, 0));
        JbtnSair.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JbtnSair.setForeground(new java.awt.Color(255, 255, 255));
        JbtnSair.setText("Sair");
        JbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSairActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnSair);
        JbtnSair.setBounds(464, 19, 60, 25);

        JlblFotoTopo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        JlblFotoTopo.setForeground(new java.awt.Color(2, 33, 65));
        jPanel1.add(JlblFotoTopo);
        JlblFotoTopo.setBounds(160, 0, 240, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 550, 90);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        JtxtPesquisar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        JtxtPesquisar.setForeground(new java.awt.Color(2, 33, 65));
        JtxtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtPesquisarActionPerformed(evt);
            }
        });
        JtxtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtPesquisarKeyPressed(evt);
            }
        });
        jPanel3.add(JtxtPesquisar);
        JtxtPesquisar.setBounds(100, 101, 260, 22);

        JbtnPesquisar.setBackground(new java.awt.Color(0, 153, 0));
        JbtnPesquisar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JbtnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnPesquisar.setText("Pesquisar");
        JbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(JbtnPesquisar);
        JbtnPesquisar.setBounds(370, 101, 100, 22);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 33, 65));
        jLabel2.setText("Nome");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 150, 40, 16);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 33, 65));
        jLabel3.setText("Email");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 150, 40, 16);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 33, 65));
        jLabel4.setText("Celular");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(350, 150, 60, 16);

        jtbPesquisa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtbPesquisa.setForeground(new java.awt.Color(2, 33, 65));
        jtbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbPesquisa);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(40, 170, 470, 150);

        jPanel2.setBackground(new java.awt.Color(211, 233, 255));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 33, 65));
        jLabel6.setText("Centro Paula Souza");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(191, 11, 170, 24);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 33, 65));
        jLabel7.setText("etecde.barueri.3?fref=ts");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(209, 41, 140, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/facebook-icon.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(191, 41, 12, 14);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 33, 65));
        jLabel1.setText("POWERED BY: FELIPE LIMA 2º TI");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 80, 200, 16);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 340, 550, 120);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, -10, 550, 460);

        setSize(new java.awt.Dimension(538, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSairActionPerformed
        // TODO add your handling code here:

        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_JbtnSairActionPerformed

    private void JbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPesquisarActionPerformed

        
        pesquisar();

    }//GEN-LAST:event_JbtnPesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        JtxtPesquisar.requestFocus();
        pesquisartudo();
        
    }//GEN-LAST:event_formWindowOpened

    private void JtxtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtPesquisarKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==evt.VK_ENTER){
        
            JbtnPesquisar.doClick();
            
        }
        
    }//GEN-LAST:event_JtxtPesquisarKeyPressed

    private void JtxtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtPesquisarActionPerformed
        // TODO add your handling code here:
        
                       
    }//GEN-LAST:event_JtxtPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnPesquisar;
    private javax.swing.JButton JbtnSair;
    private javax.swing.JLabel JlblFotoTopo;
    private javax.swing.JTextField JtxtPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbPesquisa;
    // End of variables declaration//GEN-END:variables

    public void pesquisar(){
    
        try{
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection con;

            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/bd_projeto_tcc", "root", "");

            String query = "select nome_usuario, email_usuario, telefone_usuario from usuario where nome_usuario like '%"+JtxtPesquisar.getText()+"%';";

            PreparedStatement cmd;

            cmd = con.prepareStatement(query);

            ResultSet rs;

            rs = cmd.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jtbPesquisa.getModel();

            model.setNumRows(0);

            while (rs.next()){

                model.addRow(
                    new Object[]{
                        rs.getString("nome_usuario"),
                        rs.getString("email_usuario"),
                        rs.getString("telefone_usuario")
                    }
                );

            }

        } catch(ClassNotFoundException ex){

            JOptionPane.showMessageDialog(this, "Erro de Conexão","Erro",JOptionPane.ERROR_MESSAGE);

        } catch(SQLException ex){
        
            JOptionPane.showMessageDialog(this, "Erro de Conexão","Erro",JOptionPane.ERROR_MESSAGE);

        }
    
    }
    
    public void pesquisartudo(){
    
        try{
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection con;

            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/bd_projeto_tcc", "root", "");

            String query = "select nome_usuario, telefone_usuario, email_usuario from usuario";

            PreparedStatement cmd;

            cmd = con.prepareStatement(query);

            ResultSet rs;

            rs = cmd.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jtbPesquisa.getModel();

            model.setNumRows(0);
            
            while (rs.next()){

                model.addRow(
                    new Object[]{
                        rs.getString("nome_usuario"),
                        rs.getString("email_usuario"),
                        rs.getString("telefone_usuario")
                    }
                );

            }

        } catch(ClassNotFoundException ex){

            JOptionPane.showMessageDialog(this, "Erro de Conexão","Erro",JOptionPane.ERROR_MESSAGE);

        } catch(SQLException ex){
        
            JOptionPane.showMessageDialog(this, "Erro de Conexão","Erro",JOptionPane.ERROR_MESSAGE);

        }
    
    }
    
    private void setIcon() {
    
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    
    }
    

}
