/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author Killuminati
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIcon();
        
        ImageIcon image = new ImageIcon(getClass().getResource("Etec-Cursos.png"));
        Image imag = image.getImage().getScaledInstance(JlblFotoTopo.getWidth(), JlblFotoTopo.getHeight(), Image.SCALE_SMOOTH);
        
        JlblFotoTopo.setIcon(new ImageIcon(imag));
        PromptSupport.setPrompt("Login", JtxtLogin);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, JtxtLogin);
        PromptSupport.setPrompt("Senha", JtxtSenha);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, JtxtSenha);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JlblFotoTopo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JtxtVoltar = new javax.swing.JButton();
        JtxtLogin = new javax.swing.JTextField();
        JtxtSenha = new javax.swing.JPasswordField();
        JbtnEntrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(211, 233, 255));
        jPanel1.setLayout(null);

        JlblFotoTopo.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        JlblFotoTopo.setForeground(new java.awt.Color(2, 47, 93));
        jPanel1.add(JlblFotoTopo);
        JlblFotoTopo.setBounds(130, 0, 290, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 540, 120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 39, 66));
        jLabel3.setText("apenas ao Administrador.");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(190, 190, 180, 19);

        JtxtVoltar.setBackground(new java.awt.Color(204, 0, 0));
        JtxtVoltar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JtxtVoltar.setForeground(new java.awt.Color(255, 255, 255));
        JtxtVoltar.setText("Voltar");
        JtxtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(JtxtVoltar);
        JtxtVoltar.setBounds(20, 130, 70, 25);

        JtxtLogin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        JtxtLogin.setForeground(new java.awt.Color(2, 33, 65));
        JtxtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtLoginActionPerformed(evt);
            }
        });
        JtxtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtLoginKeyPressed(evt);
            }
        });
        jPanel3.add(JtxtLogin);
        JtxtLogin.setBounds(190, 240, 170, 20);

        JtxtSenha.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        JtxtSenha.setForeground(new java.awt.Color(2, 33, 65));
        JtxtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtSenhaKeyPressed(evt);
            }
        });
        jPanel3.add(JtxtSenha);
        JtxtSenha.setBounds(190, 280, 170, 20);

        JbtnEntrar.setBackground(new java.awt.Color(0, 153, 0));
        JbtnEntrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JbtnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnEntrar.setText("Entrar");
        JbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnEntrarActionPerformed(evt);
            }
        });
        jPanel3.add(JbtnEntrar);
        JbtnEntrar.setBounds(230, 330, 90, 25);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(175, 39, 66));
        jLabel9.setText("Esta tela é designada,");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(200, 170, 160, 19);

        jPanel2.setBackground(new java.awt.Color(211, 233, 255));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 33, 65));
        jLabel5.setText("Centro Paula Souza");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 20, 170, 24);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 33, 65));
        jLabel6.setText("etecde.barueri.3?fref=ts");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(220, 50, 140, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/facebook-icon.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(200, 50, 12, 14);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 33, 65));
        jLabel1.setText("POWERED BY: FELIPE LIMA 2º TI");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 80, 200, 16);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 390, 540, 130);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, -10, 540, 520);

        setSize(new java.awt.Dimension(533, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JtxtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtVoltarActionPerformed
        // TODO add your handling code here:
        
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_JtxtVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        JtxtLogin.requestFocus();
        
    }//GEN-LAST:event_formWindowOpened

    private void JbtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnEntrarActionPerformed
        // TODO add your handling code here:
       
            logar();
        
    }//GEN-LAST:event_JbtnEntrarActionPerformed

    private void JtxtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtLoginKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==evt.VK_ENTER){
        
            JtxtSenha.requestFocus();
            
        }
        
    }//GEN-LAST:event_JtxtLoginKeyPressed

    private void JtxtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtSenhaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==evt.VK_ENTER){
        
            JbtnEntrar.doClick();
            
        }
        
    }//GEN-LAST:event_JtxtSenhaKeyPressed

    private void JtxtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private void setIcon() {
    
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnEntrar;
    private javax.swing.JLabel JlblFotoTopo;
    private javax.swing.JTextField JtxtLogin;
    private javax.swing.JPasswordField JtxtSenha;
    private javax.swing.JButton JtxtVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public void logar(){
    
        if(validacao()){
            
            try{
            
                Class.forName("com.mysql.jdbc.Driver");

                Connection con;

                con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/bd_projeto_tcc", "root", "");

                String query = "select * from administrador where login='"+JtxtLogin.getText()+"'";

                PreparedStatement cmd;

                cmd = con.prepareStatement(query);
    
                ResultSet rs;

                rs = cmd.executeQuery();
                
                rs.first();
                
                if(JtxtSenha.getText().equals(rs.getString("senha"))){
            
                        JOptionPane.showMessageDialog(this, "Login efetuado","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                        HomeAdm hmad=new HomeAdm();
                        hmad.setVisible(true);
                        this.dispose();
            
                } else{
                
                    JOptionPane.showMessageDialog(this, "Usuário ou senha invalidos.","Erro",JOptionPane.ERROR_MESSAGE);
                    JtxtSenha.requestFocus();
                    
                }
                
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erro de Conexão","Erro",JOptionPane.ERROR_MESSAGE);

            } catch (SQLException ex) {
       
                JOptionPane.showMessageDialog(this, "Você não tem acesso a essa tela.","Erro",JOptionPane.ERROR_MESSAGE);
                JtxtLogin.setText("");
                JtxtSenha.setText("");
                JtxtLogin.requestFocus();

            }
        }
    
    }
    
    public boolean validacao(){
    
        String n1 = JtxtLogin.getText().trim();
        String n2 = JtxtSenha.getText().trim();
        
        if(n1.equals("")){
        
            JOptionPane.showMessageDialog(this, "Campo vazio, por favor preencha todos os campos.",
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            JtxtLogin.requestFocus();
            return false;
        
        }
        
        if(n2.equals("")){
        
            JOptionPane.showMessageDialog(this, "Campo vazio, por favor preencha todos os campos.",
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            JtxtSenha.requestFocus();
            return false;
        
        }
        
        return true;
    
    }

}
