/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author Killuminati
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setIcon();
        //this.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 255), 1, true));
        //setBackground(Color.red);
        ImageIcon image = new ImageIcon(getClass().getResource("Etec-Cursos.png"));
        Image imag = image.getImage().getScaledInstance(JlblFotoTopo.getWidth(), JlblFotoTopo.getHeight(), Image.SCALE_SMOOTH);
        
        JlblFotoTopo.setIcon(new ImageIcon(imag));
        //this.setSize(, );      
          
        //minWidth -= DIFF_MIN_WIDTH;  
        //minHeight -= DIFF_MIN_HEIGHT; 
        //this.setUndecorated(true);
        //this.setDefaultLookAndFeelDecorated();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JlblFotoTopo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JbtnAdm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JbtnCadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JtxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JtxtTelefone = new javax.swing.JFormattedTextField();
        JtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Vistantes");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(211, 233, 255));
        jPanel1.setLayout(null);
        jPanel1.add(JlblFotoTopo);
        JlblFotoTopo.setBounds(110, 20, 330, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 540, 180);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        JbtnAdm.setBackground(new java.awt.Color(204, 0, 0));
        JbtnAdm.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JbtnAdm.setForeground(new java.awt.Color(255, 255, 255));
        JbtnAdm.setText("Administrador");
        JbtnAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAdmActionPerformed(evt);
            }
        });
        jPanel3.add(JbtnAdm);
        JbtnAdm.setBounds(390, 190, 120, 25);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 47, 93));
        jLabel9.setText("Controle de Visitantes");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(90, 230, 380, 60);

        JbtnCadastrar.setBackground(new java.awt.Color(0, 153, 0));
        JbtnCadastrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JbtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnCadastrar.setText("Registrar sua Participação");
        JbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(JbtnCadastrar);
        JbtnCadastrar.setBounds(180, 500, 190, 25);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(148, 23, 23));
        jLabel8.setText("Obrigado pela sua presença!");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(180, 570, 170, 16);

        JtxtEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        JtxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtEmailKeyPressed(evt);
            }
        });
        jPanel3.add(JtxtEmail);
        JtxtEmail.setBounds(180, 460, 200, 22);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 33, 65));
        jLabel4.setText("Email:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(140, 460, 34, 16);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 33, 65));
        jLabel3.setText("Celular:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(130, 420, 43, 16);

        try {
            JtxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JtxtTelefone.setFocusTraversalPolicyProvider(true);
        JtxtTelefone.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        JtxtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtTelefoneKeyPressed(evt);
            }
        });
        jPanel3.add(JtxtTelefone);
        JtxtTelefone.setBounds(180, 420, 200, 22);

        JtxtNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        JtxtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtNomeKeyPressed(evt);
            }
        });
        jPanel3.add(JtxtNome);
        JtxtNome.setBounds(180, 380, 200, 22);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 33, 65));
        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(140, 380, 40, 16);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(172, 35, 35));
        jLabel11.setText("pedimos que registre sua participação.\n");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 330, 230, 16);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(175, 39, 66));
        jLabel10.setText("Para melhor controle de recepção, ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(170, 310, 200, 20);

        jPanel2.setBackground(new java.awt.Color(211, 233, 255));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 33, 65));
        jLabel5.setText("Centro Paula Souza");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(183, 11, 170, 24);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/facebook-icon.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(195, 53, 12, 16);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 33, 65));
        jLabel6.setText("etecde.barueri.3?fref=ts");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(213, 53, 140, 16);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 33, 65));
        jLabel1.setText("POWERED BY: FELIPE LIMA 2º TI");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 80, 200, 16);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 610, 550, 120);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, -10, 540, 730);

        setSize(new java.awt.Dimension(529, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCadastrarActionPerformed
        // TODO add your handling code here:
        
        insert();
        
    }//GEN-LAST:event_JbtnCadastrarActionPerformed

    private void JbtnAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAdmActionPerformed
        // TODO add your handling code here:
        
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_JbtnAdmActionPerformed

    private void JtxtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtNomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
        
            JtxtTelefone.requestFocus();
            
        }
    }//GEN-LAST:event_JtxtNomeKeyPressed

    private void JtxtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtTelefoneKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
        
            JtxtEmail.requestFocus();
            
        }
    }//GEN-LAST:event_JtxtTelefoneKeyPressed

    private void JtxtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtEmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
        
            JbtnCadastrar.doClick();
            
        }
    }//GEN-LAST:event_JtxtEmailKeyPressed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        JtxtNome.requestFocus();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnAdm;
    private javax.swing.JButton JbtnCadastrar;
    private javax.swing.JLabel JlblFotoTopo;
    private javax.swing.JTextField JtxtEmail;
    private javax.swing.JTextField JtxtNome;
    private javax.swing.JFormattedTextField JtxtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public boolean validacao(){
        
        String n1 = JtxtNome.getText().trim();
        String n2 = JtxtTelefone.getText().trim();
        String n3 = JtxtEmail.getText().trim();
        
        if(n1.equals("")){
        
            JOptionPane.showMessageDialog(this, "Campo vazio, por favor preencha todos os campos para melhor controle.",
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            JtxtNome.requestFocus();
            return false;
        
        } else if(n2.equals("")){
        
            JOptionPane.showMessageDialog(this, "Campo vazio, por favor preencha todos os campos para melhor controle.",
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            JtxtTelefone.requestFocus();
            return false;
        
        } else if(n3.equals("")){
        
            JOptionPane.showMessageDialog(this, "Campo vazio, por favor preencha todos os campos para melhor controle.",
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            JtxtEmail.requestFocus();
            return false;
        
        } else{
        
            Pattern p = Pattern.compile("\\b(^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9-]+)*((\\.[A-Za-z0-9]{2,})|(\\.[A-Za-z0-9]{2,}\\.[A-Za-z0-9]{2,}))$)\\b");
        
            Matcher m = p.matcher(n3);
        
            boolean matchFound = m.matches();
        
            if(matchFound){
        
                return true;
            
            } else{
        
                JOptionPane.showMessageDialog(this, "Email invalido.",
                        "Erro", 
                        JOptionPane.ERROR_MESSAGE);
                JtxtEmail.setText("");
                JtxtEmail.requestFocus();
            
                return false;
        
            }
              
        }
        
    }
   
    public void insert(){
    
        if(validacao()){
            
            try{
            
                Class.forName("com.mysql.jdbc.Driver");

                Connection con;

                con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/bd_projeto_tcc", "root", "");

                String query = "select * from usuario where email_usuario='"+JtxtEmail.getText()+"'";

                PreparedStatement cmd;

                cmd = con.prepareStatement(query);
    
                ResultSet rs;

                rs = cmd.executeQuery();
                
                rs.first();
                
                
                if(JtxtEmail.getText().equals(rs.getString("email_usuario"))){
                
                    JOptionPane.showMessageDialog(this, "Você já registrou sua participação.","Erro", JOptionPane.ERROR_MESSAGE);
                    JtxtNome.setText("");
                    JtxtTelefone.setText("");
                    JtxtEmail.setText("");
                    JtxtNome.requestFocus();
                    
                } 
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erro de Conexão","Erro",JOptionPane.ERROR_MESSAGE);

            } catch (SQLException ex) {
       
                try {
                        
                        Class.forName("com.mysql.jdbc.Driver");
            
                        Connection con2;
                        
                        con2 = DriverManager.getConnection("jdbc:mysql://127.0.0.1/bd_projeto_tcc", "root", "");
                        
                        String query2 = "insert into usuario(nome_usuario, telefone_usuario, email_usuario) values(?,?,?);";
            
                        PreparedStatement stmt = con2.prepareStatement(query2);
            
                        stmt.setString(1, JtxtNome.getText());
                        stmt.setString(2, JtxtTelefone.getText());
                        stmt.setString(3, JtxtEmail.getText());
            
                        stmt.executeUpdate();
            
                        JOptionPane.showMessageDialog(this, "Cadastrado com sucesso.\nVolte Sempre","Sucesso no Cadastro", JOptionPane.INFORMATION_MESSAGE);
            
                        JtxtNome.setText("");
                        JtxtTelefone.setText("");
                        JtxtEmail.setText("");
                        JtxtNome.requestFocus();
                        
                        stmt.close();
                        con2.close();
                    
                    } catch (SQLException ex1) {
                    
                        JOptionPane.showMessageDialog(this, "Erro de conexão.","Erro", JOptionPane.ERROR_MESSAGE);
                   
                    } catch (ClassNotFoundException ex1) {
                        
                        JOptionPane.showMessageDialog(this, "Erro na classe.","Erro", JOptionPane.ERROR_MESSAGE);
                   
                    }
                
            }
        }
            
        
    }

    private void setIcon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    
    }

    /*private void setBorder() {
        Border borderForte = BorderFactory.createLineBorder(Color.GREEN, 3); 
        Border borderForteVermelha = BorderFactory.createLineBorder(Color.RED, 3); 
        Border borderNormal = BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1); 
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 255), 1, true));
        //setBorder(); 
        //setBorder(borderForte);
    }*/
    
}
